### ISSUE TITLE
Can't Launch Program.

### ISSUE THREAD

**Issue by Swipperr** [HellPie/DungeonTools#5]
I Cant Launch The Program, It Only Bring's Up Cmd To I Guess Attempt To Launch But Get's Stopped Almost Immediately
[bandicam 2020-08-18 03-25-40-897.zip](https://github.com/HellPie/DungeonTools/files/5359448/bandicam.2020-08-18.03-25-40-897.zip)

**Comment by ZingBallyhoo** [comment]
wrong video?

**Comment by HellPie** [comment]
idk what that video was, but you either need to manually open the command prompt and execute the program by hand or you drag and drop files onto it, if you double click the executable it's going to start up, see you didn't tell it anything about what to do and it will close itself immediately because that's how command line tools work.
